<?php

namespace Database\Seeders;

use App\Models\Skill;
use App\Models\SkillAlias;
use Illuminate\Database\Seeder;

class SkillCatalogSeeder extends Seeder
{
    private array $catalog = [
        'Programming languages' => [
            ['name' => 'PHP', 'aliases' => []],
            ['name' => 'JavaScript', 'aliases' => ['JS', 'ECMAScript', 'ES6', 'ES2015']],
            ['name' => 'TypeScript', 'aliases' => ['TS']],
            ['name' => 'Python', 'aliases' => ['Python 3']],
            ['name' => 'Java', 'aliases' => ['Java 8', 'Java 11', 'Java 17', 'Java 21']],
            ['name' => 'C#', 'aliases' => ['C Sharp', 'C#.NET']],
            ['name' => 'Go', 'aliases' => ['Golang']],
            ['name' => 'Rust', 'aliases' => ['Rust Lang']],
            ['name' => 'Ruby', 'aliases' => []],
            ['name' => 'Kotlin', 'aliases' => []],
            ['name' => 'Swift', 'aliases' => []],
            ['name' => 'Dart', 'aliases' => []],
            ['name' => 'Scala', 'aliases' => []],
            ['name' => 'SQL', 'aliases' => ['Structured Query Language']],
            ['name' => 'HTML', 'aliases' => ['HTML5']],
            ['name' => 'CSS', 'aliases' => ['CSS3', 'Cascading Style Sheets']],
            ['name' => 'Shell Scripting', 'aliases' => ['Bash', 'Shell', 'Zsh']],
            ['name' => 'C++', 'aliases' => ['CPP']],
            ['name' => 'C', 'aliases' => ['C Language']],
            ['name' => 'R', 'aliases' => ['R Language']],
        ],
        'Frameworks & libraries' => [
            ['name' => 'Laravel', 'aliases' => ['Laravel Framework']],
            ['name' => 'Vue.js', 'aliases' => ['Vue', 'Vue 3', 'VueJS', 'Vue 2']],
            ['name' => 'React', 'aliases' => ['React.js', 'ReactJS', 'React 18']],
            ['name' => 'Angular', 'aliases' => ['Angular 2+', 'Angular 17', 'Angular CLI']],
            ['name' => 'Symfony', 'aliases' => ['Symfony Framework']],
            ['name' => 'Django', 'aliases' => ['Django Framework', 'Django REST']],
            ['name' => 'Spring Boot', 'aliases' => ['Spring', 'Spring Framework']],
            ['name' => 'ASP.NET Core', 'aliases' => ['ASP.NET', '.NET Core', 'Dotnet Core']],
            ['name' => 'Node.js', 'aliases' => ['Node', 'NodeJS', 'Express.js', 'Express']],
            ['name' => 'Next.js', 'aliases' => ['NextJS']],
            ['name' => 'Nuxt.js', 'aliases' => ['Nuxt', 'NuxtJS', 'Nuxt 3']],
            ['name' => 'Tailwind CSS', 'aliases' => ['Tailwind', 'TailwindCSS']],
            ['name' => 'Bootstrap', 'aliases' => ['Bootstrap 5', 'Bootstrap 4']],
            ['name' => 'jQuery', 'aliases' => []],
            ['name' => 'Sass', 'aliases' => ['SCSS', 'Sassy CSS']],
            ['name' => 'Livewire', 'aliases' => ['Laravel Livewire']],
            ['name' => 'Alpine.js', 'aliases' => ['AlpineJS', 'Alpine']],
            ['name' => 'Inertia.js', 'aliases' => ['Inertia']],
            ['name' => 'Flask', 'aliases' => []],
            ['name' => 'FastAPI', 'aliases' => []],
            ['name' => 'Ruby on Rails', 'aliases' => ['Rails', 'RoR']],
            ['name' => 'Flutter', 'aliases' => []],
            ['name' => 'React Native', 'aliases' => []],
            ['name' => 'Electron', 'aliases' => ['Electron.js']],
            ['name' => 'Three.js', 'aliases' => ['ThreeJS']],
            ['name' => 'Chart.js', 'aliases' => []],
            ['name' => 'D3.js', 'aliases' => ['D3']],
            ['name' => 'TensorFlow', 'aliases' => ['TF']],
            ['name' => 'PyTorch', 'aliases' => []],
            ['name' => 'Pandas', 'aliases' => []],
            ['name' => 'NumPy', 'aliases' => []],
            ['name' => 'Jest', 'aliases' => []],
            ['name' => 'Vitest', 'aliases' => []],
            ['name' => 'Pest', 'aliases' => ['Pest PHP']],
            ['name' => 'PHPUnit', 'aliases' => []],
            ['name' => 'Cypress', 'aliases' => []],
            ['name' => 'Playwright', 'aliases' => []],
        ],
        'Databases' => [
            ['name' => 'MySQL', 'aliases' => ['MariaDB']],
            ['name' => 'PostgreSQL', 'aliases' => ['Postgres', 'PG']],
            ['name' => 'MongoDB', 'aliases' => ['Mongo']],
            ['name' => 'Redis', 'aliases' => []],
            ['name' => 'SQLite', 'aliases' => []],
            ['name' => 'Elasticsearch', 'aliases' => ['ES', 'Elastic']],
            ['name' => 'Firebase', 'aliases' => ['Firebase Realtime Database', 'Firestore']],
            ['name' => 'Supabase', 'aliases' => []],
            ['name' => 'Oracle Database', 'aliases' => ['Oracle', 'Oracle DB', 'Oracle SQL']],
            ['name' => 'Microsoft SQL Server', 'aliases' => ['SQL Server', 'MSSQL']],
        ],
        'Tools & version control' => [
            ['name' => 'Git', 'aliases' => []],
            ['name' => 'GitHub', 'aliases' => []],
            ['name' => 'GitLab', 'aliases' => []],
            ['name' => 'Bitbucket', 'aliases' => []],
            ['name' => 'Docker', 'aliases' => ['Docker Engine', 'Docker Compose']],
            ['name' => 'Kubernetes', 'aliases' => ['K8s', 'Kube']],
            ['name' => 'Composer', 'aliases' => []],
            ['name' => 'npm', 'aliases' => ['Node Package Manager']],
            ['name' => 'Yarn', 'aliases' => []],
            ['name' => 'Webpack', 'aliases' => []],
            ['name' => 'Vite', 'aliases' => ['Vite.js']],
            ['name' => 'ESLint', 'aliases' => []],
            ['name' => 'Prettier', 'aliases' => []],
            ['name' => 'PHPStan', 'aliases' => []],
            ['name' => 'Pint', 'aliases' => ['Laravel Pint']],
            ['name' => 'PHP CS Fixer', 'aliases' => []],
            ['name' => 'Jira', 'aliases' => ['JIRA']],
            ['name' => 'Trello', 'aliases' => []],
            ['name' => 'Notion', 'aliases' => []],
            ['name' => 'Slack', 'aliases' => []],
            ['name' => 'Discord', 'aliases' => []],
            ['name' => 'Postman', 'aliases' => ['Postman API']],
            ['name' => 'Insomnia', 'aliases' => []],
            ['name' => 'Swagger', 'aliases' => ['OpenAPI', 'Swagger UI']],
            ['name' => 'Figma', 'aliases' => ['Figma Design']],
            ['name' => 'VS Code', 'aliases' => ['Visual Studio Code', 'VSCode']],
            ['name' => 'PHPStorm', 'aliases' => ['PhpStorm', 'JetBrains PHPStorm']],
            ['name' => 'IntelliJ IDEA', 'aliases' => ['IntelliJ']],
            ['name' => 'n8n', 'aliases' => []],
            ['name' => 'Make', 'aliases' => ['Integromat', 'Make.com']],
            ['name' => 'Zapier', 'aliases' => []],
        ],
        'Cloud & DevOps' => [
            ['name' => 'AWS', 'aliases' => ['Amazon Web Services']],
            ['name' => 'Amazon EC2', 'aliases' => ['EC2']],
            ['name' => 'Amazon S3', 'aliases' => ['S3']],
            ['name' => 'AWS Lambda', 'aliases' => ['Lambda']],
            ['name' => 'Azure', 'aliases' => ['Microsoft Azure']],
            ['name' => 'Google Cloud Platform', 'aliases' => ['GCP', 'Google Cloud']],
            ['name' => 'Cloudflare', 'aliases' => []],
            ['name' => 'Vercel', 'aliases' => []],
            ['name' => 'Netlify', 'aliases' => []],
            ['name' => 'GitHub Actions', 'aliases' => ['GHA', 'GitHub CI/CD']],
            ['name' => 'GitLab CI', 'aliases' => ['GitLab CI/CD']],
            ['name' => 'Jenkins', 'aliases' => []],
            ['name' => 'Terraform', 'aliases' => []],
            ['name' => 'Ansible', 'aliases' => []],
            ['name' => 'Nginx', 'aliases' => ['nginx']],
            ['name' => 'Apache', 'aliases' => ['Apache HTTP Server']],
            ['name' => 'cPanel', 'aliases' => []],
            ['name' => 'Laravel Forge', 'aliases' => ['Forge']],
            ['name' => 'Laravel Vapor', 'aliases' => ['Vapor']],
        ],
        'Methodologies & practices' => [
            ['name' => 'Agile', 'aliases' => ['Agile Methodology']],
            ['name' => 'Scrum', 'aliases' => ['Scrum Framework']],
            ['name' => 'Kanban', 'aliases' => []],
            ['name' => 'CI/CD', 'aliases' => ['Continuous Integration', 'Continuous Deployment', 'Continuous Delivery']],
            ['name' => 'TDD', 'aliases' => ['Test Driven Development']],
            ['name' => 'REST APIs', 'aliases' => ['RESTful APIs', 'REST']],
            ['name' => 'GraphQL', 'aliases' => []],
            ['name' => 'Microservices', 'aliases' => []],
            ['name' => 'Event-Driven Architecture', 'aliases' => ['Event Sourcing', 'EDA']],
            ['name' => 'OOP', 'aliases' => ['Object-Oriented Programming']],
            ['name' => 'SOLID', 'aliases' => ['SOLID Principles']],
            ['name' => 'Design Patterns', 'aliases' => []],
            ['name' => 'API Design', 'aliases' => ['API Development']],
            ['name' => 'Database Design', 'aliases' => ['Database Modeling', 'ERD']],
            ['name' => 'Unit Testing', 'aliases' => ['Unit Test']],
            ['name' => 'Integration Testing', 'aliases' => ['Integration Test']],
            ['name' => 'E2E Testing', 'aliases' => ['End-to-End Testing', 'E2E']],
            ['name' => 'Code Review', 'aliases' => ['Peer Review']],
            ['name' => 'UX Design', 'aliases' => ['User Experience', 'UX']],
        ],
        'Soft skills' => [
            ['name' => 'Communication', 'aliases' => ['Verbal Communication', 'Written Communication']],
            ['name' => 'Teamwork', 'aliases' => ['Collaboration', 'Team Collaboration']],
            ['name' => 'Problem Solving', 'aliases' => ['Analytical Thinking', 'Critical Thinking']],
            ['name' => 'Time Management', 'aliases' => []],
            ['name' => 'Leadership', 'aliases' => []],
            ['name' => 'Adaptability', 'aliases' => ['Flexibility']],
            ['name' => 'Creativity', 'aliases' => ['Creative Thinking']],
            ['name' => 'Attention to Detail', 'aliases' => []],
            ['name' => 'Conflict Resolution', 'aliases' => []],
            ['name' => 'Mentoring', 'aliases' => ['Coaching']],
            ['name' => 'Public Speaking', 'aliases' => ['Presentation Skills']],
            ['name' => 'Active Listening', 'aliases' => []],
            ['name' => 'Empathy', 'aliases' => []],
            ['name' => 'Self-Motivation', 'aliases' => ['Self Discipline']],
            ['name' => 'Remote Collaboration', 'aliases' => ['Remote Work', 'Distributed Teams']],
        ],
        'Operating systems & platforms' => [
            ['name' => 'Linux', 'aliases' => ['Ubuntu', 'Debian', 'CentOS', 'Red Hat']],
            ['name' => 'Windows', 'aliases' => ['Windows Server']],
            ['name' => 'macOS', 'aliases' => ['OS X']],
            ['name' => 'WordPress', 'aliases' => ['WP']],
            ['name' => 'Shopify', 'aliases' => []],
            ['name' => 'Stripe', 'aliases' => ['Stripe API']],
            ['name' => 'Twilio', 'aliases' => []],
            ['name' => 'SendGrid', 'aliases' => []],
            ['name' => 'Mailchimp', 'aliases' => []],
            ['name' => 'OpenAI API', 'aliases' => ['OpenAI', 'GPT API', 'ChatGPT API']],
            ['name' => 'Google Analytics', 'aliases' => ['GA', 'GA4']],
            ['name' => 'Google Maps API', 'aliases' => ['Google Maps']],
            ['name' => 'OAuth', 'aliases' => ['OAuth 2.0', 'OAuth2']],
            ['name' => 'JWT', 'aliases' => ['JSON Web Tokens', 'JSON Web Token']],
            ['name' => 'WebSockets', 'aliases' => ['Web Socket', 'WS']],
            ['name' => 'Pusher', 'aliases' => []],
            ['name' => 'Laravel Reverb', 'aliases' => ['Reverb']],
            ['name' => 'Laravel Horizon', 'aliases' => ['Horizon']],
            ['name' => 'Laravel Telescope', 'aliases' => ['Telescope']],
            ['name' => 'Laravel Nova', 'aliases' => ['Nova']],
            ['name' => 'Laravel Breeze', 'aliases' => ['Breeze']],
            ['name' => 'Laravel Jetstream', 'aliases' => ['Jetstream']],
            ['name' => 'Laravel Sanctum', 'aliases' => ['Sanctum']],
            ['name' => 'Laravel Cashier', 'aliases' => ['Cashier']],
            ['name' => 'Laravel Scout', 'aliases' => ['Scout']],
            ['name' => 'Laravel Socialite', 'aliases' => ['Socialite']],
            ['name' => 'Laravel Pulse', 'aliases' => ['Pulse']],
            ['name' => 'Laravel Folio', 'aliases' => ['Folio']],
            ['name' => 'Laravel Pennant', 'aliases' => ['Pennant']],
        ],
    ];

    public function run(): void
    {
        foreach ($this->catalog as $category => $skills) {
            foreach ($skills as $skillData) {
                $skill = Skill::create([
                    'name' => $skillData['name'],
                    'normalized_name' => strtolower($skillData['name']),
                    'category' => $category,
                    'is_active' => true,
                ]);

                foreach ($skillData['aliases'] as $alias) {
                    SkillAlias::create([
                        'skill_id' => $skill->id,
                        'alias' => $alias,
                    ]);
                }
            }
        }
    }
}
